@param int totalDEestudantes
<!doctype html>
<html long="pt-BR">
<head><meta charset="UTF-8">
    <title>Cadastro de estudantes</title>
    <link rel="stylesheet" href="/css/enfeite.css">
</head>
<body>
    <img src="/images/images.png" alt="IFPB Campus Cajazeiras">
    <h1>Sistema de Cadastros de Estudantes</h1>
    <p>Estudante cadastros: ${totalDEestudantes}</p>
    <a href="/estudantes/novo">Cadastrar estudantes</a>
</body>
</html>